Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: This is a security group
      GroupName: MySecurityGroup
      VpcId: vpc-0903c296c25c460c6

  MyNewEC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-0be29bafdaad782db
      InstanceType: t2.micro
      SubnetId: subnet-00da935be165aae80
      SecurityGroupIds: 
        - sg-0d1cc5903dc0e791f
      KeyName: login1
  
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: nilesh93